core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('survey.urls')),
]

survey/urls.py
from __future__ import annotations

from django.urls import path

from survey import views

app_name = "survey"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "validate-email-address/",
        views.validate_email_address,
        name="validate_email_address"
    ),
    path(
        "validate-phone-number/",
        views.validate_phone_number,
        name="validate_phone_number"
    ),
]

survey/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class TimeStamped(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Survey(TimeStamped):
    name = models.CharField(_("Your name"), max_length=400)
    phone_number = models.CharField(
        _("Your phone number"), max_length=13, blank=True)
    email_address = models.EmailField(_("Your email"), blank=True)
    comment = models.TextField(_("Tell us about your experience"))
    rate_one = models.PositiveIntegerField(
        _("Rate your experience"), default=1)
    rate_two = models.PositiveIntegerField(
        _("Are you willing to recommend us? Rate us"), default=1)
    contact = models.BooleanField(
        _("Would you like us to contact you?"), default=0)
    
    class Meta:
        pass

    def __str__(self):
        return f'Survey by: {self.name}'

survey/forms.py
from __future__ import annotations

from django import forms
from django.utils.translation import gettext_lazy as _

from django_email_blacklist import DisposableEmailChecker

from survey.models import Survey
from secure.input_utils import is_valid_email, is_valid_phone_number



email_checker = DisposableEmailChecker()


class EmailForm(forms.Form):
    email_address = forms.EmailField()

    def clean(self):
        cleaned_data = super().clean()
        email_address = cleaned_data.get('email_address')
        if not is_valid_email(email_address):
            raise forms.ValidationError(
                _("The e-mail address you provide is not valid")
            )
        if email_checker.is_disposable(email_address):
            raise forms.ValidationError(
                _("The e-mail address you provide is prohibited")
            )

class PhoneNumberForm(forms.Form):
    phone_number = forms.CharField()

    def clean(self):
        cleaned_data = super().clean()
        phone_number = cleaned_data.get('phone_number')
        if not is_valid_phone_number(phone_number.replace("-", "")):
            raise forms.ValidationError(
                _("The phone number you provide is not valid")
            )


class SurveyForm(forms.ModelForm):

    class Meta:
        model = Survey
        exclude = ('rate_one', 'rate_two', 'contact',)

survey/views.py
from __future__ import annotations

from django.http import HttpRequest
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from django.views.decorators.http import require_POST

from django_htmx.http import trigger_client_event
from django_htmx.middleware import HtmxDetails

from secure.input_utils import find_possible_field_error

from survey.forms import EmailForm
from survey.forms import PhoneNumberForm
from survey.forms import SurveyForm


class HtmxHttpRequest(HttpRequest):
    htmx: HtmxDetails


def response_field_validation(
    possible_message_error: str, field_name: str) -> HttpResponse:
    return trigger_client_event(
        HttpResponse(status=202),
        "loadError",
        {
            "is_there_error": len(possible_message_error) > 0,
            "field_name": f"id_{field_name}",
            "message_error": possible_message_error
        }
    )


@require_http_methods(["GET", "POST",])
def index(request: HtmxHttpRequest) -> HttpResponse:
    form = SurveyForm(request.POST or None)
    if request.htmx and request.POST:
        if form.is_valid():
            form.save()
            return trigger_client_event(
                HttpResponse(status=202),
                "saveComplete",
                {
                    "success": True
                }
            )
    return render(request, "survey/index.html", 
        {
            "form": form
        }
    )


@require_POST
def validate_email_address(request: HtmxHttpRequest) -> HttpResponse:
    possible_message_error, field_name = find_possible_field_error(
        request, EmailForm)
    return response_field_validation(possible_message_error, field_name)


@require_POST
def validate_phone_number(request: HtmxHttpRequest) -> HttpResponse:
    possible_message_error, field_name = find_possible_field_error(
        request, PhoneNumberForm)
    return response_field_validation(possible_message_error, field_name)

survey/templates/survey/index.html
{% extends 'layouts/base.html' %}

{% load widget_tweaks %}

{% block title %}Petty Survey 0.1{% endblock %}

{% block page_title %}Petty Survey 0.1{% endblock %}

{% block content %}
<form hx-post="{% url 'survey:index' %}" hx-target="this" hx-swap="none" id="survey-form">
    <div class="form-floating mb-3">
        {% render_field form.name class="form-control" autocomplete="off" %}
        <label for="id_name">{{ form.name.label }}</label>
    </div>

    <div class="row">
        <div class="form-floating mb-3 col-6">
            <input type="email" name="{{ form.email_address.name }}" id="id_email_address" class="form-control" autocomplete="off"
                hx-post="{% url 'survey:validate_email_address' %}" hx-target="#id_email_address_error_message" hx-include="this">
            <label for="id_email_address">{{ form.email_address.label }}</label>
            <div class='invalid-feedback' id="id_email_address_error_message"></div>
        </div>
        <div class="form-floating mb-3 col-6">
            <input type="text" name="{{ form.phone_number.name }}" id="id_phone_number" class="form-control" autocomplete="off"
                hx-post="{% url 'survey:validate_phone_number' %}" hx-target="#id_phone_number_error_message" hx-include="this">
            <label for="id_phone_number">{{ form.phone_number.label }}</label>
            <div class='invalid-feedback' id="id_phone_number_error_message"></div>
        </div>
    </div>

    <div class="form-floating mb-3">
        {% render_field form.comment class="form-control" autocomplete="off" %}
        <label for="id_comment">{{ form.comment.label }}</label>
    </div>

    <div class="text-center">
        <button type="submit" class="btn btn-primary btn-lg btn-pill" id="surveybtn">Send survey</button>
    </div>
</form>
{% endblock %}

templates/layouts/base.html
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}{% endblock %}</title>
    <!-- CSS files -->
    <link rel="stylesheet" href="{% static 'css/tabler.min.css' %}">
    <style>
        @import url('https://rsms.me/inter/inter.css');

        :root {
            --tblr-font-sans-serif: 'Inter Var', -apple-system, BlinkMacSystemFont, San Francisco, Segoe UI, Roboto, Helvetica Neue, sans-serif;
        }

        body {
            font-feature-settings: "cv03", "cv04", "cv11";
        }
    </style>
    <!--JS-->
    <script src="{% static 'js/htmx.min.js' %}"></script>
    <script src="//cdn.jsdelivr.net/npm/vanilla-masker@1.1.1/build/vanilla-masker.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>

<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    <div class="page">
        <div class="page-wrapper">
            <div class="page-body">
                <div class="container-xl">
                    <div class="row row-cards">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">{% block page_title %}{% endblock %}</h3>
                                </div>
                                <div class="card-body">
                                    {% block content %}
                                    {% endblock %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'js/app.js' %}"></script>
</body>

</html>